# Generated by Django 4.1.3 on 2022-12-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(verbose_name='Количество вопросов'),
        ),
    ]
