# Generated by Django 4.1.3 on 2022-12-07 11:27

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, validators=[quiz.models.validate_correct_checkin], verbose_name='Правильно'),
        ),
    ]
